services:
    phlexible_sitemap.simple_node_url_generator:
        class: Phlexible\Bundle\SitemapBundle\Sitemap\SimpleNodeUrlGenerator
        public: false
        arguments:
            - "@router"
            - "@event_dispatcher"

    phlexible_sitemap.country_node_urlset_generator:
        class: Phlexible\Bundle\SitemapBundle\Sitemap\CountryNodeUrlsetGenerator
        public: false
        arguments:
            - "@phlexible_country_context.country_collection"
            - "@phlexible_sitemap.node_url_generator"

    phlexible_sitemap.language_node_urlset_generator:
        class: Phlexible\Bundle\SitemapBundle\Sitemap\LanguageNodeUrlsetGenerator
        public: false
        arguments:
            - "@phlexible_sitemap.node_url_generator"

    phlexible_sitemap.sitemap_generator:
        class: Phlexible\Bundle\SitemapBundle\Sitemap\SitemapGenerator
        arguments:
            - "@phlexible_tree.content_tree_manager"
            - "@phlexible_sitemap.node_urlset_generator"
            - "@event_dispatcher"
            - "%phlexible_cms.languages.available%"

    phlexible_sitemap.caching_sitemap_generator:
        class: Phlexible\Bundle\SitemapBundle\Sitemap\CachingSitemapGenerator
        arguments:
            - "@phlexible_sitemap.sitemap_generator"
            - "%phlexible_sitemap.cache_dir%"

    # commands
    phlexible_sitemap.build_command:
        class: Phlexible\Bundle\SitemapBundle\Command\BuildCommand
        arguments:
            - "@phlexible_sitemap.caching_sitemap_generator"
            - "@phlexible_siteroot.siteroot_manager"
        tags:
            - { name: console.command }

    # controllers
    phlexible_sitemap.sitemap_controller:
        class: Phlexible\Bundle\SitemapBundle\Controller\SitemapController
        arguments:
            - "@phlexible_sitemap.caching_sitemap_generator"
            - "@phlexible_siteroot.siteroot_request_matcher"
