coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
            before_left_brace:
                function: true

checks:
    php:
        verify_property_names: true
        return_doc_comments: true
        uppercase_constants: true
        use_self_instead_of_fqcn: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        newline_at_end_of_file: true
        more_specific_types_in_doc_comments: true
        line_length:
            max_length: '120'
        function_in_camel_caps: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_line_ending: true
        classes_in_camel_caps: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        align_assignments: false
        no_short_method_names:
            minimum: '3'
        encourage_postdec_operator: true

